package com.atakavuncu.booktime.ui.navigation

object Route {
    const val MAIN = "main"
    const val AUTH = "auth"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val CREATE_PROFILE = "create-profile"
    const val MENU = "menu"
    const val BOOKS = "books"
    const val DISCOVER = "discover"
    const val PROFILE = "profile"
    const val ALL_BOOKS = "all-books"
    const val BOOK_DETAIL = "book-detail/{bookId}"
    const val FAVORITES = "favorites"
    const val LISTS = "lists"
    const val LIST_DETAIL = "list-detail"
    const val ACCOUNT_SETTINGS = "account-settings"
    const val EMAIL_UPDATE = "email-update"
    const val PASSWORD_UPDATE = "password-update"
    const val DELETE_ACCOUNT = "delete-account"
    const val APP_SETTINGS = "app-settings"
    const val LANGUAGE_SETTINGS = "language-settings"
    const val THEME_SETTINGS = "theme-settings"
    const val PRIVACY_AND_SAFETY = "privacy-and-safety"
    const val KVKK = "kvkk"
    const val PRIVACY_POLICY = "privacy-policy"
    const val FAQ = "faq"
    const val FAQ_ACCOUNT_AND_PROFILE = "faq-account-and-profile"
    const val FAQ_BOOKS = "faq-books"
    const val FAQ_SETTINGS = "faq-settings"
    const val ABOUT_US = "about-us"
    const val LOG_OUT = "log-out"
}